name: NetworkStorage
version: ${project.version}
main: com.dermoha.networkstorage.NetworkStoragePlugin
api-version: 1.21
author: DerMoha
description: A networked storage system for Minecraft servers, make sharing storage easy!

commands:
  storage:
    description: Main command for NetworkStorage
    usage: /<command> [wand|terminal|info|reset|confirm-reset|cancel-reset|help|wireless]
    aliases: [ns, netstorage]
  network:
    description: Manages networks
    usage: /<command> [create|edit|rename|select|list]
    aliases: [net]
  networkstorage:
    description: Admin commands for NetworkStorage
    usage: /<command> [reload]

permissions:
  networkstorage.*:
    description: All NetworkStorage permissions
    default: op
    children:
      networkstorage.wand: true
      networkstorage.terminal: true
      networkstorage.wireless: true
      networkstorage.give.wand: true
      networkstorage.give.terminal: true
      networkstorage.give.wireless: true
      networkstorage.reset: true
      networkstorage.access.all: true
      networkstorage.admin: true

  networkstorage.wand:
    description: Allows using storage wands
    default: true

  networkstorage.terminal:
    description: Allows placing storage terminal blocks
    default: true

  networkstorage.wireless:
    description: Allows using wireless terminals
    default: true

  networkstorage.give.wand:
    description: Allows getting storage wands with commands
    default: op

  networkstorage.give.terminal:
    description: Allows getting storage terminal blocks with commands
    default: op

  networkstorage.give.wireless:
    description: Allows getting wireless terminals with commands
    default: op

  networkstorage.reset:
    description: Allows resetting own storage network
    default: true

  networkstorage.access.all:
    description: Allows accessing any storage network
    default: op

  networkstorage.admin:
    description: Administrative permissions for NetworkStorage
    default: op
    children:
      networkstorage.network.create: true
      networkstorage.network.edit: true
      networkstorage.network.rename: true
      networkstorage.wireless: true
      networkstorage.give.wand: true
      networkstorage.give.terminal: true
      networkstorage.give.wireless: true

  networkstorage.network.create:
    description: Allows creating new networks
    default: op

  networkstorage.network.edit:
    description: Allows editing existing networks
    default: op

  networkstorage.network.rename:
    description: Allows renaming existing networks
    default: op
